/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoogleTasksRouteImport } from './routes/google-tasks'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeminiInsightsRouteImport } from './routes/api/gemini-insights'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAskRouteImport } from './routes/api/ask'

const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleTasksRoute = GoogleTasksRouteImport.update({
  id: '/google-tasks',
  path: '/google-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiInsightsRoute = ApiGeminiInsightsRouteImport.update({
  id: '/api/gemini-insights',
  path: '/api/gemini-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/google-tasks': typeof GoogleTasksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/template': typeof TemplateRoute
  '/api/ask': typeof ApiAskRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gemini-insights': typeof ApiGeminiInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/google-tasks': typeof GoogleTasksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/template': typeof TemplateRoute
  '/api/ask': typeof ApiAskRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gemini-insights': typeof ApiGeminiInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/google-tasks': typeof GoogleTasksRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/template': typeof TemplateRoute
  '/api/ask': typeof ApiAskRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gemini-insights': typeof ApiGeminiInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/google-tasks'
    | '/login'
    | '/sitemap.xml'
    | '/template'
    | '/api/ask'
    | '/api/chat'
    | '/api/gemini-insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/google-tasks'
    | '/login'
    | '/sitemap.xml'
    | '/template'
    | '/api/ask'
    | '/api/chat'
    | '/api/gemini-insights'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/google-tasks'
    | '/login'
    | '/sitemap.xml'
    | '/template'
    | '/api/ask'
    | '/api/chat'
    | '/api/gemini-insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  GoogleTasksRoute: typeof GoogleTasksRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplateRoute: typeof TemplateRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGeminiInsightsRoute: typeof ApiGeminiInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-tasks': {
      id: '/google-tasks'
      path: '/google-tasks'
      fullPath: '/google-tasks'
      preLoaderRoute: typeof GoogleTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-insights': {
      id: '/api/gemini-insights'
      path: '/api/gemini-insights'
      fullPath: '/api/gemini-insights'
      preLoaderRoute: typeof ApiGeminiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  GoogleTasksRoute: GoogleTasksRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplateRoute: TemplateRoute,
  ApiAskRoute: ApiAskRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGeminiInsightsRoute: ApiGeminiInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
